# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7b4738ad769259c6ee00f8219c861a5f8b3730f76b1d09c5f6735e493aca11cdaa84a0c3bdb76214092abe818c77f389aecdae18b7a99ad8219dde159e4915d

test:
  secret_key_base: 99a73f8499557f93138015914ed39a34ab05e1e38a65eb623ef245e821d3eb40d68bee689a2051b598672c74264cb731b8fa038979c64cb083178f5bd4e423ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
